Unable to create submission journals if approval_hierarchy is installed
OpusVL/mtd pull request #87
Opened 2021-04-27 11:13 UTC by DaeronAlagos

If the approval_hierarchy module is installed as well as the mtd module, when the VAT is submitted, the current user may not have permission to post a move.line for the VAT submission values.

Fixes #16990

2021-04-27 13:23 UTC, Nick-OpusVL requested changes
OK mostly, but with_user is not intended for bypassing access rights checks - use sudo() for that unless somehow it doesn't work in this particular case.

https://www.odoo.com/documentation/13.0/reference/orm.html#altering-the-environment

The difference with sudo is it doesn't actually change the user, so things like audit trail messages, From addresses for emails (if any), default company etc won't be affected by it.

2021-04-27 13:23 UTC, Nick-OpusVL commented on account_mtd_vat/models/mtd_vat_issue_request.py
> +        account_move_id.with_user(SUPERUSER_ID).action_post()
```suggestion
        account_move_id.sudo().action_post()
```

2021-04-27 13:23 UTC, Nick-OpusVL commented on account_mtd_vat/models/mtd_vat_issue_request.py
> +from odoo import models, fields, api, exceptions, SUPERUSER_ID
```suggestion
from odoo import models, fields, api, exceptions
```

2021-04-27 13:27 UTC, Nick-OpusVL commented
@DaeronAlagos please heed the warnings about sudo() in the link I posted you though.

2021-04-27 13:31 UTC, DaeronAlagos commented
Good spot. Now I need to go and check what method is being used in approval_hierarchy to check the user permissions. I'll re-request once I've made the correct change.

2021-04-28 08:09 UTC, DaeronAlagos commented
I think you're correct about this to be using .sudo() instead of .with_user() in a normal scenario. Unfortunately approval_hierarchy is using a custom method to check the user (id==SUPERUSER_ID or login='admin'). I'm not going to change it to .sudo() here as that will require greater changes to approval_hierarchy.

2021-04-28 08:10 UTC, DaeronAlagos commented
I'm not going to merge this once approved. I will update RM submodule to point to this commit so it can be tested on staging before being merged and deployed to production.

2021-04-28 08:27 UTC, Nick-OpusVL approved these changes
OK then.

2021-05-25 14:15 UTC, merged